#! /usr/bin/env python3

######################################################################
#  Users can execute this script to install Nexus in a simple way.   #
#                                                                    #
#  This script performs a path-based installation of Nexus by        #
#  updating the PATH and PYTHONPATH environment variables in a       # 
#  user's .bashrc file (or similar for other shells):                #
#                                                                    #
#    export PATH=/your/path/to/nexus/bin:$PATH                       #
#    export PYTHONPATH=/your/path/to/nexus:$PYTHONPATH               #
#                                                                    #
#  Text similar to this is added directly to the end of the rc file. #
#                                                                    #
#  In this example, this script (install) resides at:                # 
#                                                                    #
#    /your/path/to/nexus/install                                     #
#                                                                    #
#  Since these path environment variables are added to a user's      #
#  shell configuration file, they will have persistent access to     #
#  Nexus' binaries and be able to create operational Nexus workflow  #
#  scripts each time they login to their machine.                    #
#                                                                    #
#  See the README for more details.                                  #
#                                                                    #
######################################################################


import os
import sys
import shutil

#=======#
# setup #
#=======#

# define usage
usage = 'usage: "install <rc_file>"'

# find paths to install script and source directory
installer  = os.path.realpath(__file__)
source_dir = os.path.dirname(installer)
lib_dir    = os.path.join(source_dir,'nexus')
bin_dir    = os.path.join(source_dir,'bin')

# function to report errors
def error(msg):
    print('\nmanual_install error: '+msg+'\n')
    sys.exit(1)


#================#
# main execution #
#================#

# extract force flag
args = sys.argv[1:]
force = False
if '-f' in args:
    args.pop(args.index('-f'))
    force = True

# determine config file and shell from user-provided rc file path
if len(args)==0 or len(args) > 2:
    error('\ninstall takes the path to an rc file and an optional shell name.'
          f'\n\nFor example: {sys.argv[0]} ~/.bashrc'
          f'\nOr         : {sys.argv[0]} ~/.profile bash'
          '\n\nSupported shells are: bash, zsh, tcsh, csh, and ksh.')

rc_file = os.path.expanduser(args[0])
if not os.path.exists(rc_file):
    error('specified config (rc) file "{0}" does not exist'.format(rc_file))

rc_name = os.path.basename(rc_file)

def infer_shell_from_rc(rc_name):
    if 'bash' in rc_name:
        return 'bash'
    if 'zsh' in rc_name:
        return 'zsh'
    if 'tcsh' in rc_name:
        return 'tcsh'
    if 'csh' in rc_name:
        return 'csh'
    if 'ksh' in rc_name:
        return 'ksh'
    error('could not infer shell type from rc file name "{0}"'.format(rc_name))

if len(args) == 2:
    # shell explicitly provided by user
    shell = args[1]
else:
    # infer shell from rc file name
    shell = infer_shell_from_rc(rc_name)

# get format for setting env variables in shell
set_env_formats = dict(
    ksh  = 'export {0}={1}\n',
    csh  = 'setenv {0} {1}\n',
    tcsh = 'setenv {0} {1}\n',
    bash = 'export {0}={1}\n',
    zsh  = 'export {0}={1}\n',
    )
if shell not in set_env_formats:
    error('shell "{0}" is not supported; must be one of: {1}'.format(shell,', '.join(sorted(set_env_formats.keys()))))
set_env_fmt = set_env_formats[shell]

header_start = '### added by Nexus '
header = '### added by Nexus installer ###'
footer = '### end Nexus additions ###'
paths  = set_env_fmt.format('PATH',bin_dir+':$PATH')
paths += set_env_fmt.format('PYTHONPATH',lib_dir+':$PYTHONPATH')

path_install  = header+'\n'
path_install += paths
path_install += footer+'\n'

if not force:
    print('\nThe following will be appended to file "{}"'.format(rc_file))
    print()
    print(path_install)
    print()
    response = input('Do you want to proceed? [y/n]')
    if response.lower() not in ('y','yes'):
        print('\nNexus installation aborted.')
        print('No changes have been made to file "{}"\n'.format(rc_file))
        sys.exit(0)

# add lib path to PYTHONPATH in config file
shutil.copy2(rc_file,rc_file+'-nexus.bak')
f = open(rc_file,'r')
rc_contents = f.read()
f.close()
if header_start in rc_contents and footer in rc_contents:
    header_loc = rc_contents.find(header_start)
    footer_loc = rc_contents.find(footer)
    before_header = rc_contents[:header_loc]
    after_footer  = rc_contents[footer_loc+len(footer):]
    rc_contents = before_header + after_footer
rc_contents = rc_contents.rstrip()+'\n\n\n'
rc_contents += path_install
f = open(rc_file,'w')
f.write(rc_contents)
f.close()

print('\nNexus installation complete.')
print(f'\nExecute "source {rc_file}" to make Nexus available in the current session.\n')

